<?php
/**
 * Created by PhpStorm.
 * User: tea
 * Date: 7/6/18
 * Time: 6:54 PM
 */

namespace frontend\widgets\sidebar;

use common\models\Brands;
use yii\base\Widget;
use yii\data\Pagination;

class SidebarWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $brands = Brands::find()->asArray()->all();

        return $this->render('sidebar',['brands'=>$brands]);
    }

}