<?php
namespace frontend\widgets\categories;

use common\models\Categories;

class CategoryWidget extends \yii\base\Widget
{

    public $tpl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->tpl)){
            $this->tpl = 'slider';
        }else{
            $this->tpl = 'categories';
        }
    }

    public function run()
    {
        // TODO get categories dynamic from db and pass to view
        $categories = Categories::find()->orderBy(['id'=>SORT_DESC])->limit(8)->asArray()->all();
        return $this->render($this->tpl,
                [
                    'categories' => $categories,
                ]
            );
    }

}