<?php
namespace frontend\widgets\brands;


use common\models\Brands;

class BrandsWidget extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // TODO get brands dynamic from db and pass to view
        $brands = Brands::find()->orderBy(['id'=>SORT_ASC])->asArray()->all();
        return $this->render('brands',
                [
                    'brands' => $brands
                ]
            );
    }
}