<?php
namespace frontend\widgets\slider;

class SliderWidget extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // TODO get slider images dynamic from db and pass to view
        return $this->render('slider');
    }

}